language: go

go:
  - 1.7

install:
    - go get github.com/mattn/goveralls
    - go get -t -v ./...

script:
    - go vet -x
    - go test -v -race
    - go test -v -race github.com/funny/link/codec
    - go test -v -covermode=count -coverprofile=profile.cov

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci