language: go

go:
  - 1.7

install:
    - go get github.com/mattn/goveralls
    - go get -t -v ./...

script:
    - go vet -x
    - go test -covermode=count -coverprofile=profile.cov -v
    - go test -v github.com/funny/link/codec

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci